Rearranged jobs so they flow logically

diff --git a/.github/workflows/publish-docker-image.yml b/.github/workflows/publish-docker-image.yml
--- a/.github/workflows/publish-docker-image.yml
+++ b/.github/workflows/publish-docker-image.yml
@@ -5,6 +5,16 @@ on:
     types: [completed]
 
 jobs:
+  notify_failure:
+    name: "Check if test succeeded"
+    runs-on: ubuntu-latest
+    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+    steps:
+      - name: Test of 750words-client failed, not publishing new Docker image
+        run: |
+          echo "::error::Test of 750words-client failed, not publishing new Docker image."
+          exit 1
+
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
@@ -32,13 +42,3 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: ${{ github.repository }}
           short-description: ${{ github.event.repository.description }}
-
-  notify_failure:
-    name: "Produce error message"
-    runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
-    steps:
-      - name: Error message
-        run: |
-          echo "::error::Test of 750words-client failed, not publishing new Docker image."
-          exit 1
